### PR TITLE
added dockerfile

### PR DESCRIPTION
**Pull request by rishvantsingh**
#33 Hello @kordiseps I have added the dockerfile. Kindly review and update the PR.

### CODE REVIEW

**Comment by saidyeter** [comment]
Hello @rishvantsingh, thanks for effort. I am truly grateful.
I am going to review it.
By the way I want to close this issue with #35.
I want to read a file that contains a list of directories(for host computer) which is currently in `./server/vars.json` 
and mount them into a folder like `/home` directory.
Do you have any idea?

**Comment by rishvantsingh** [comment]
Okkh i will try and let you know.

**Comment by rishvantsingh** [comment]
While running use the -v flag with docker run /host/directory:/container/directory to mount it.
example : docker run -v " your path "

**Comment by saidyeter** [comment]
Thanks for effort. I am gonna change dockerfile after changing algorithm.

**Pull request merged**
